import { RecommendationTool } from './models/recommendation.model';

export const RECOMMENDATION_TOOL_CATALOG = [
  {
    id: 'breathing',
    title: 'Breathing',
    icon: 'radio-button-on-outline',
    category: 'therapeutic',
    description: 'A short breathing reset for calming the body and creating a pause.',
    titleTranslations: { en: 'Breathing', he: 'נשימה' },
    descriptionTranslations: {
      en: 'A short breathing reset for calming the body and creating a pause.',
      he: 'איפוס נשימה קצר להרגעת הגוף ויצירת רגע של עצירה.',
    },
    matchingEmotions: ['Anxious', 'Stressed', 'Overwhelmed', 'Angry', 'Tired'],
    matchingInfluences: ['Work', 'School', 'Health', 'Sleep'],
    matchingPreferences: ['breathing', 'calm', 'quick reset', 'quiet', 'body-based'],
    supportedMoodRange: [1, 6],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'grounding',
    title: 'Grounding',
    icon: 'scan-outline',
    category: 'therapeutic',
    description: 'A senses-based grounding exercise for anxious, stressed, or scattered moments.',
    titleTranslations: { en: 'Grounding', he: 'קרקוע' },
    descriptionTranslations: {
      en: 'A senses-based grounding exercise for anxious, stressed, or scattered moments.',
      he: 'תרגול קרקוע דרך החושים לרגעים של חרדה, לחץ או פיזור.',
    },
    matchingEmotions: ['Anxious', 'Stressed', 'Overwhelmed', 'Frustrated', 'Lonely'],
    matchingInfluences: ['Work', 'School', 'News', 'Social media', 'Money'],
    matchingPreferences: ['grounding', 'senses', 'quick reset', 'present moment'],
    supportedMoodRange: [1, 5],
    supportedModes: ['support'],
  },
  {
    id: 'meditation',
    title: 'Meditation',
    icon: 'leaf-outline',
    category: 'therapeutic',
    description: 'A quiet meditation practice for settling attention and softening tension.',
    titleTranslations: { en: 'Meditation', he: 'מדיטציה' },
    descriptionTranslations: {
      en: 'A quiet meditation practice for settling attention and softening tension.',
      he: 'תרגול מדיטציה שקט לייצוב הקשב וריכוך מתח.',
    },
    matchingEmotions: ['Calm', 'Anxious', 'Stressed', 'Tired', 'Relaxed'],
    matchingInfluences: ['Health', 'Sleep', 'Work', 'School'],
    matchingPreferences: ['meditation', 'mindfulness', 'quiet', 'focus'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'guided-journaling',
    title: 'Guided Journaling',
    icon: 'create-outline',
    category: 'therapeutic',
    description: 'Structured journaling prompts for naming what is happening and what is needed.',
    titleTranslations: { en: 'Guided Journaling', he: 'כתיבה מונחית' },
    descriptionTranslations: {
      en: 'Structured journaling prompts for naming what is happening and what is needed.',
      he: 'שאלות כתיבה מובנות לזיהוי מה קורה ומה נחוץ עכשיו.',
    },
    matchingEmotions: ['Sad', 'Anxious', 'Lonely', 'Frustrated', 'Hopeful'],
    matchingInfluences: ['Family', 'Partner', 'Friends', 'Work', 'Health'],
    matchingPreferences: ['journaling', 'writing', 'reflection', 'self-awareness'],
    supportedMoodRange: [1, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'gratitude',
    title: 'Gratitude',
    icon: 'sparkles-outline',
    category: 'therapeutic',
    description: 'A brief gratitude practice for reconnecting with small sources of steadiness.',
    titleTranslations: { en: 'Gratitude', he: 'הכרת תודה' },
    descriptionTranslations: {
      en: 'A brief gratitude practice for reconnecting with small sources of steadiness.',
      he: 'תרגול תודה קצר לחיבור מחדש לדברים קטנים שמייצבים.',
    },
    matchingEmotions: ['Grateful', 'Hopeful', 'Happy', 'Sad', 'Lonely'],
    matchingInfluences: ['Family', 'Friends', 'Partner', 'Health', 'Hobbies'],
    matchingPreferences: ['gratitude', 'reflection', 'positive focus', 'journaling'],
    supportedMoodRange: [3, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'reflection-prompts',
    title: 'Reflection Prompts',
    icon: 'chatbubble-ellipses-outline',
    category: 'therapeutic',
    description: 'A thoughtful prompt to explore the moment without needing to solve it immediately.',
    titleTranslations: { en: 'Reflection Prompts', he: 'שאלות לרפלקציה' },
    descriptionTranslations: {
      en: 'A thoughtful prompt to explore the moment without needing to solve it immediately.',
      he: 'שאלה עדינה לחקירת הרגע בלי צורך לפתור אותו מיד.',
    },
    matchingEmotions: ['Calm', 'Focused', 'Hopeful', 'Sad', 'Frustrated'],
    matchingInfluences: ['Work', 'Family', 'Friends', 'Hobbies', 'Other'],
    matchingPreferences: ['reflection', 'prompts', 'journaling', 'self-awareness'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'muscle-relaxation',
    title: 'Muscle Relaxation',
    icon: 'body-outline',
    category: 'therapeutic',
    description: 'A progressive muscle relaxation practice for releasing physical stress.',
    titleTranslations: { en: 'Muscle Relaxation', he: 'הרפיית שרירים' },
    descriptionTranslations: {
      en: 'A progressive muscle relaxation practice for releasing physical stress.',
      he: 'תרגול הרפיית שרירים הדרגתית לשחרור מתח גופני.',
    },
    matchingEmotions: ['Stressed', 'Anxious', 'Tired', 'Angry', 'Overwhelmed'],
    matchingInfluences: ['Work', 'Health', 'Fitness', 'Sleep'],
    matchingPreferences: ['body-based', 'relaxation', 'stress relief', 'quiet'],
    supportedMoodRange: [1, 5],
    supportedModes: ['support'],
  },
  {
    id: 'music',
    title: 'Music',
    icon: 'musical-notes-outline',
    category: 'personal',
    description: 'Listen to music that matches or gently shifts the current mood.',
    titleTranslations: { en: 'Music', he: 'מוזיקה' },
    descriptionTranslations: {
      en: 'Listen to music that matches or gently shifts the current mood.',
      he: 'להקשיב למוזיקה שמתאימה למצב הרוח או מזיזה אותו בעדינות.',
    },
    matchingEmotions: ['Sad', 'Happy', 'Excited', 'Relaxed', 'Lonely'],
    matchingInfluences: ['Friends', 'Travel', 'Hobbies', 'Other'],
    matchingPreferences: ['music', 'creative', 'comfort', 'energy shift'],
    supportedMoodRange: [1, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'walking',
    title: 'Walking',
    icon: 'walk-outline',
    category: 'personal',
    description: 'Take a short walk to add movement, space, and a change of scene.',
    titleTranslations: { en: 'Walking', he: 'הליכה' },
    descriptionTranslations: {
      en: 'Take a short walk to add movement, space, and a change of scene.',
      he: 'הליכה קצרה שמוסיפה תנועה, מרחב ושינוי אווירה.',
    },
    matchingEmotions: ['Stressed', 'Tired', 'Frustrated', 'Focused', 'Hopeful'],
    matchingInfluences: ['Work', 'Fitness', 'Health', 'Weather'],
    matchingPreferences: ['walking', 'movement', 'outdoors', 'body-based'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'nature',
    title: 'Nature',
    icon: 'flower-outline',
    category: 'personal',
    description: 'Spend a few minutes near plants, sky, sunlight, or fresh air.',
    titleTranslations: { en: 'Nature', he: 'טבע' },
    descriptionTranslations: {
      en: 'Spend a few minutes near plants, sky, sunlight, or fresh air.',
      he: 'כמה דקות ליד צמחים, שמיים, אור שמש או אוויר פתוח.',
    },
    matchingEmotions: ['Anxious', 'Stressed', 'Sad', 'Calm', 'Grateful'],
    matchingInfluences: ['Weather', 'Health', 'Travel', 'Hobbies'],
    matchingPreferences: ['nature', 'outdoors', 'quiet', 'calm'],
    supportedMoodRange: [1, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'photography',
    title: 'Photography',
    icon: 'camera-outline',
    category: 'personal',
    description: 'Notice and capture one image that reflects the day or the current feeling.',
    titleTranslations: { en: 'Photography', he: 'צילום' },
    descriptionTranslations: {
      en: 'Notice and capture one image that reflects the day or the current feeling.',
      he: 'לשים לב ולצלם תמונה אחת שמשקפת את היום או התחושה.',
    },
    matchingEmotions: ['Focused', 'Happy', 'Grateful', 'Hopeful', 'Calm'],
    matchingInfluences: ['Hobbies', 'Travel', 'Weather', 'Other'],
    matchingPreferences: ['photography', 'creative', 'outdoors', 'noticing'],
    supportedMoodRange: [3, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'reading',
    title: 'Reading',
    icon: 'book-outline',
    category: 'personal',
    description: 'Read something gentle, interesting, or absorbing for a short reset.',
    titleTranslations: { en: 'Reading', he: 'קריאה' },
    descriptionTranslations: {
      en: 'Read something gentle, interesting, or absorbing for a short reset.',
      he: 'לקרוא משהו עדין, מעניין או סוחף לאיפוס קצר.',
    },
    matchingEmotions: ['Tired', 'Calm', 'Focused', 'Sad', 'Relaxed'],
    matchingInfluences: ['School', 'Sleep', 'Hobbies', 'Other'],
    matchingPreferences: ['reading', 'quiet', 'learning', 'comfort'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'cooking',
    title: 'Cooking',
    icon: 'restaurant-outline',
    category: 'personal',
    description: 'Make or prepare something simple that feels nourishing or enjoyable.',
    titleTranslations: { en: 'Cooking', he: 'בישול' },
    descriptionTranslations: {
      en: 'Make or prepare something simple that feels nourishing or enjoyable.',
      he: 'להכין משהו פשוט שמרגיש מזין או נעים.',
    },
    matchingEmotions: ['Tired', 'Grateful', 'Happy', 'Calm', 'Lonely'],
    matchingInfluences: ['Food', 'Family', 'Health', 'Hobbies'],
    matchingPreferences: ['cooking', 'food', 'hands-on', 'comfort'],
    supportedMoodRange: [3, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'friends',
    title: 'Friends',
    icon: 'people-circle-outline',
    category: 'personal',
    description: 'Reach out to a friend or plan a small point of connection.',
    titleTranslations: { en: 'Friends', he: 'חברים' },
    descriptionTranslations: {
      en: 'Reach out to a friend or plan a small point of connection.',
      he: 'לפנות לחבר או לתכנן רגע קטן של חיבור.',
    },
    matchingEmotions: ['Lonely', 'Happy', 'Excited', 'Sad', 'Hopeful'],
    matchingInfluences: ['Friends', 'Social media', 'Travel', 'Other'],
    matchingPreferences: ['friends', 'connection', 'social', 'support'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'family',
    title: 'Family',
    icon: 'people-outline',
    category: 'personal',
    description: 'Connect with family in a way that feels supportive and realistic today.',
    titleTranslations: { en: 'Family', he: 'משפחה' },
    descriptionTranslations: {
      en: 'Connect with family in a way that feels supportive and realistic today.',
      he: 'להתחבר למשפחה בדרך שתומכת ומתאימה להיום.',
    },
    matchingEmotions: ['Lonely', 'Grateful', 'Sad', 'Hopeful', 'Happy'],
    matchingInfluences: ['Family', 'Partner', 'Food', 'Travel'],
    matchingPreferences: ['family', 'connection', 'support', 'care'],
    supportedMoodRange: [2, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'sports',
    title: 'Sports',
    icon: 'football-outline',
    category: 'personal',
    description: 'Use sports, movement, or a game as an energizing outlet.',
    titleTranslations: { en: 'Sports', he: 'ספורט' },
    descriptionTranslations: {
      en: 'Use sports, movement, or a game as an energizing outlet.',
      he: 'להשתמש בספורט, תנועה או משחק כפורקן שנותן אנרגיה.',
    },
    matchingEmotions: ['Excited', 'Focused', 'Frustrated', 'Proud', 'Happy'],
    matchingInfluences: ['Fitness', 'Health', 'Friends', 'Hobbies'],
    matchingPreferences: ['sports', 'movement', 'competition', 'energy'],
    supportedMoodRange: [3, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'gaming',
    title: 'Gaming',
    icon: 'game-controller-outline',
    category: 'personal',
    description: 'Play something light or absorbing as a contained break.',
    titleTranslations: { en: 'Gaming', he: 'משחקים' },
    descriptionTranslations: {
      en: 'Play something light or absorbing as a contained break.',
      he: 'לשחק משהו קליל או סוחף כהפסקה תחומה.',
    },
    matchingEmotions: ['Tired', 'Bored', 'Happy', 'Focused', 'Lonely'],
    matchingInfluences: ['Friends', 'Hobbies', 'Social media', 'Other'],
    matchingPreferences: ['gaming', 'play', 'focus', 'comfort'],
    supportedMoodRange: [3, 7],
    supportedModes: ['support', 'growth'],
  },
  {
    id: 'learn-something-new',
    title: 'Learn Something New',
    icon: 'school-outline',
    category: 'growth',
    description: 'Choose a small topic or lesson that sparks curiosity without pressure.',
    titleTranslations: { en: 'Learn Something New', he: 'ללמוד משהו חדש' },
    descriptionTranslations: {
      en: 'Choose a small topic or lesson that sparks curiosity without pressure.',
      he: 'לבחור נושא קטן או שיעור שמעורר סקרנות בלי לחץ.',
    },
    matchingEmotions: ['Curious', 'Hopeful', 'Focused', 'Excited', 'Proud'],
    matchingInfluences: ['School', 'Work', 'Hobbies', 'Other'],
    matchingPreferences: ['learning', 'curiosity', 'skill-building', 'focus'],
    supportedMoodRange: [5, 7],
    supportedModes: ['growth'],
  },
  {
    id: 'personal-goals',
    title: 'Personal Goals',
    icon: 'flag-outline',
    category: 'growth',
    description: 'Review or choose one small goal that would make the next step clearer.',
    titleTranslations: { en: 'Personal Goals', he: 'מטרות אישיות' },
    descriptionTranslations: {
      en: 'Review or choose one small goal that would make the next step clearer.',
      he: 'לבחון או לבחור מטרה קטנה שמבהירה את הצעד הבא.',
    },
    matchingEmotions: ['Hopeful', 'Focused', 'Proud', 'Excited', 'Grateful'],
    matchingInfluences: ['Work', 'School', 'Health', 'Money', 'Hobbies'],
    matchingPreferences: ['goals', 'planning', 'progress', 'self-awareness'],
    supportedMoodRange: [5, 7],
    supportedModes: ['growth'],
  },
  {
    id: 'habits',
    title: 'Habits',
    icon: 'repeat-outline',
    category: 'growth',
    description: 'Pick one tiny habit cue or repeatable action for the day.',
    titleTranslations: { en: 'Habits', he: 'הרגלים' },
    descriptionTranslations: {
      en: 'Pick one tiny habit cue or repeatable action for the day.',
      he: 'לבחור סימן קטן להרגל או פעולה שאפשר לחזור עליה היום.',
    },
    matchingEmotions: ['Focused', 'Hopeful', 'Proud', 'Calm', 'Grateful'],
    matchingInfluences: ['Health', 'Fitness', 'Sleep', 'Food', 'Work'],
    matchingPreferences: ['habits', 'routine', 'planning', 'progress'],
    supportedMoodRange: [4, 7],
    supportedModes: ['growth'],
  },
  {
    id: 'hobbies',
    title: 'Hobbies',
    icon: 'color-palette-outline',
    category: 'growth',
    description: 'Spend a little time with a hobby that feels meaningful or enjoyable.',
    titleTranslations: { en: 'Hobbies', he: 'תחביבים' },
    descriptionTranslations: {
      en: 'Spend a little time with a hobby that feels meaningful or enjoyable.',
      he: 'להקדיש מעט זמן לתחביב שמרגיש משמעותי או מהנה.',
    },
    matchingEmotions: ['Happy', 'Excited', 'Focused', 'Relaxed', 'Hopeful'],
    matchingInfluences: ['Hobbies', 'Friends', 'Travel', 'Other'],
    matchingPreferences: ['hobbies', 'play', 'creative', 'skill-building'],
    supportedMoodRange: [4, 7],
    supportedModes: ['growth'],
  },
  {
    id: 'creativity',
    title: 'Creativity',
    icon: 'brush-outline',
    category: 'growth',
    description: 'Make, sketch, write, build, or remix something small for expression.',
    titleTranslations: { en: 'Creativity', he: 'יצירתיות' },
    descriptionTranslations: {
      en: 'Make, sketch, write, build, or remix something small for expression.',
      he: 'ליצור, לצייר, לכתוב, לבנות או לערבב משהו קטן לביטוי עצמי.',
    },
    matchingEmotions: ['Excited', 'Focused', 'Hopeful', 'Happy', 'Frustrated'],
    matchingInfluences: ['Hobbies', 'School', 'Work', 'Other'],
    matchingPreferences: ['creative', 'hands-on', 'expression', 'play'],
    supportedMoodRange: [4, 7],
    supportedModes: ['growth'],
  },
  {
    id: 'personal-development',
    title: 'Personal Development',
    icon: 'trending-up-outline',
    category: 'growth',
    description: 'Reflect on a strength, lesson, or next step that supports personal growth.',
    titleTranslations: { en: 'Personal Development', he: 'התפתחות אישית' },
    descriptionTranslations: {
      en: 'Reflect on a strength, lesson, or next step that supports personal growth.',
      he: 'להתבונן בחוזקה, בלמידה או בצעד הבא שתומכים בצמיחה אישית.',
    },
    matchingEmotions: ['Hopeful', 'Proud', 'Focused', 'Grateful', 'Calm'],
    matchingInfluences: ['Work', 'School', 'Health', 'Relationships', 'Other'],
    matchingPreferences: ['self-awareness', 'growth', 'learning', 'reflection'],
    supportedMoodRange: [5, 7],
    supportedModes: ['growth'],
  },
] satisfies readonly RecommendationTool[];
